### ISSUE TITLE
std::error::Error is now implemented

### ISSUE THREAD

**Issue by ngirard** [benkay86/nom-tutorial#6]
Hey, thank you for your efforts in creating this tutorial, much appreciated !

You may want to take into account that `std::error::Error` and `std::fmt::Display` traits were [recently implemented](https://github.com/Geal/nom/pull/1043) for `nom::Err` and already made available in the subsequent releases.

Cheers!

**Comment by benkay86** [comment]
Thank you for pointing this out.  This is definitely going to make all my nom coding a lot easier!  I have updated the tutorial to remove the `ParseError` type for encapsulating nom errors since it is no longer necessary.
